version: '3.9'

x-prod-env-variables: &prod-env-variables
  LOGGER_LEVEL: info

x-mm-bot: &mm-bot-service
  deploy:
    replicas: 1
  env_file:
    - .env
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: 1
  image: mm-bot:1.0.1
  restart: unless-stopped

services:
  bingx-mm-bot:
    <<: *mm-bot-service
    environment:
      <<: *prod-env-variables
      
      APP_NAME: mm-bot
      SERVICE_NAME: bingx-mm-bot
      EXCHANGE_NAME: bingx
      ORACLE_EXCHANGE_NAME: bybit
      SYMBOL: STOP-USDT
      ORACLE_SYMBOL: STOPUSDT
      ORDER_BOOK_DEPTH: 10
      AMOUNT_DECIMALS_PRECISION: 3
      PRICE_DECIMALS_PRECISION: 5
      
      SPREAD_PRICE_LOW_END_MARGIN: 0.002
      SPREAD_PRICE_HIGH_END_MARGIN: 0.1
      SPREAD_MIN_BASE_ASSET_TRADE_VALUE: 20
      SPREAD_MIN_QUOTE_ASSET_TRADE_VALUE: 1
      SPREAD_BASE_ASSET_BUDGET_RATIO: 0.5
      SPREAD_QUOTE_ASSET_BUDGET_RATIO: 0.5
      
      VOLUME_MIN_TRADE_AMOUNT: 1200
      VOLUME_MAX_TRADE_AMOUNT: 2000
      VOLUME_PRICE_MARGIN_LOWER: 0.05
      VOLUME_PRICE_MARGIN_UPPER: 0.95
      VOLUME_PRICE_CANDLE_HEIGHT: 0.005

      UPDATE_INTERVAL_MS: 10000
    build:
      # Note:
      # The image is built only once by running "docker compose build".
      # The image is then referred by other services via the name tag. 
      context: .
      dockerfile: Dockerfile
    container_name: bingx-mm-bot
    command: >
      node ./dist/main.js
